#!/usr/bin/perl -i -p

BEGIN {
	$prefix=shift;
	$ver=shift;
	$libdir=shift;
}

if (/INSTALLDIR_AUTOREPLACE/) {
	$_=qq{my \$installdir="$prefix";};
}
elsif (/VERSION_AUTOREPLACE/) {
	$_=qq{our \$version="$ver";};
}
elsif (/^use lib/) {
	if (grep { $_ eq $libdir } @INC) {
		$_="";
	}
	else {
		$_="use lib '$libdir';\n";
	}
}
elsif ($. == 1 && ($ENV{NOTAINT} || ! exists $ENV{NOTAINT}) && m{^(#!.*perl.*?) -T$}) {
	$_=qq{$1\n};
}
elsif (/^\$ENV{PATH}="(.*)";/) {
	$_="\$ENV{PATH}=\"$1:$prefix/bin\";\n";
}
