#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# rst — xml-rpc-based ikiwiki plugin to process RST files
#
# TODO: the top of this file should be converted to a python library for
# ikiwiki plugins
# 
# based a little bit on rst.pm by Sergio Talens-Oliag, but only a little bit. :)
#
# Copyright © martin f. krafft <madduck@madduck.net>
# Released under the terms of the GNU GPL version 2
#
__name__ = 'rst'
__description__ = 'xml-rpc-based ikiwiki plugin to process RST files'
__version__ = '0.2'
__author__ = 'martin f. krafft <madduck@madduck.net>'
__copyright__ = 'Copyright © ' + __author__
__licence__ = 'GPLv2'

from docutils.core import publish_parts;
from proxy import IkiWikiProcedureProxy

def rst2html(*kwargs):
    # FIXME arguments should be treated as a hash, the order could change
    # at any time and break this.
    parts = publish_parts(kwargs[3], writer_name='html',
                          settings_overrides = { 'halt_level': 6
                                               , 'file_insertion_enabled': 0
                                               , 'raw_enabled': 1
                                               })
    return '\n'.join(parts['html_body'].splitlines()[1:-1])

import sys
def debug(s):
    sys.stderr.write(__name__ + ':DEBUG:%s' % s)
    sys.stderr.flush()

proxy = IkiWikiProcedureProxy(__name__, debug_fn=None)
proxy.register_hook('htmlize', rst2html)
proxy.run()
