#!/bin/sh
set -e
#DEBHELPER#

# Change this when some incompatible change is made that requires
# rebuilding all wikis.
firstcompat=1.1

wikilist=/etc/ikiwiki/wikilist

processline () {
	user="$1"
	setup="$2"
	
	if [ -z "$user" ] || [ -z "$setup" ]; then
		echo "parse failure in /etc/ikiwiki/wikilist, line: '$user $setup'" >&2
		exit 1
	fi
	
	if [ ! -f "$setup" ]; then
		echo "warning: $setup specified in /etc/ikiwiki/wikilist does not exist, skipping" >&2
	else
		echo "Rebuilding $setup as user $user ..."
		su "$user" -c "ikiwiki -setup $setup"
	fi
}

if [ "$1" = configure ] && [ -e $wikilist ] && \
   dpkg --compare-versions "$2" lt "$firstcompat"; then
	grep -v '^#' $wikilist | grep -v '^$' | while read line; do 
		processline $line
	done
fi
