#!/bin/sh
set -e
#DEBHELPER#

# Change this when some incompatible change is made that requires
# rebuilding all wikis.
firstcompat=2.30

if [ "$1" = configure ] && \
   dpkg --compare-versions "$2" lt "$firstcompat"; then
	ikiwiki-mass-rebuild
else
	ikiwiki-mass-rebuild -refresh -wrappers
fi
